### ISSUE TITLE
Error with clean install

### ISSUE THREAD

**Issue by FunPsycho** [hassio-addons/addon-nginx-proxy-manager#16]
# Problem/Motivation

> Getting an error after starting the add on

## Actual behavior

> Getting this error in the log

[5/17/2019] [10:17:19 PM] [Global   ] › ✖  error     Unexpected string /opt/nginx-proxy-manager/node_modules/ajv/lib/data.js:4
 0'multipleOf',
  ^^^^^^^^^^^^
SyntaxError: Unexpected string
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/node_modules/ajv/lib/ajv.js:10:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

## Steps to reproduce

> Just start the add on

**Comment by FunPsycho** [comment]
Raspberry Pi 3 B+

**Comment by tjorim** [comment]
Please provide the full log, which includes more information about your system.

**Comment by FunPsycho** [comment]
Do you need the log that is at /config/home-assistant.log?
I'll enable my logger and then send over the file when I get some data.  Here is what it says now, don't know if it's relevant or not.....

[home-assistant.log](https://github.com/hassio-addons/addon-nginx-proxy-manager/files/3194293/home-assistant.log)

**Comment by tjorim** [comment]
No, only the log at the bottom of the add-on page.

**Comment by FunPsycho** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Nginx Proxy Manager
 Manage Nginx proxy hosts with a simple, powerful interface
-----------------------------------------------------------
 Add-on version: 0.1.0
 You are running the latest version of this add-on.
 System: HassOS 2.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.93.1
 Supervisor version: 163
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

**Comment by FunPsycho** [comment]
installation should now be secure.
Thanks for using MariaDB!
Warning: World-writable config file '/etc/my.cnf' is ignored
Warning: World-writable config file '/etc/my.cnf' is ignored
Warning: World-writable config file '/etc/my.cnf' is ignored
2019-05-18 12:39:07 0 [Note] /usr/bin/mysqld (initiated by: unknown): Normal shutdown
2019-05-18 12:39:07 0 [Note] Event Scheduler: Purging the queue. 0 events
2019-05-18 12:39:07 0 [Note] InnoDB: FTS optimize thread exiting.
2019-05-18 12:39:07 0 [Note] InnoDB: Starting shutdown...
2019-05-18 12:39:07 0 [Note] InnoDB: Dumping buffer pool(s) to /data/mysql/ib_buffer_pool
2019-05-18 12:39:07 0 [Note] InnoDB: Buffer pool(s) dump completed at 190518 12:39:07
2019-05-18 12:39:10 0 [Note] InnoDB: Shutdown completed; log sequence number 1631167; transaction id 24
2019-05-18 12:39:10 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2019-05-18 12:39:10 0 [Note] /usr/bin/mysqld: Shutdown complete
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] npm.sh: executing... 
[12:39:11] INFO: Generating dummy SSL certificate
Generating a RSA private key
................................................................................................+++++
.....................+++++
writing new private key to '/data/nginx/dummykey.pem'
-----
[cont-init.d] npm.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:39:15] INFO: Starting NGinx...
[12:39:15] INFO: Starting DNSMasq...
[12:39:15] INFO: Starting MySQL database server...
Warning: World-writable config file '/etc/my.cnf' is ignored
2019-05-18 12:39:15 0 [Note] /usr/bin/mysqld (mysqld 10.3.13-MariaDB) starting as process 614 ...
2019-05-18 12:39:16 0 [Note] InnoDB: Using Linux native AIO
2019-05-18 12:39:16 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-05-18 12:39:16 0 [Note] InnoDB: Uses event mutexes
2019-05-18 12:39:16 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2019-05-18 12:39:16 0 [Note] InnoDB: Number of pools: 1
2019-05-18 12:39:16 0 [Note] InnoDB: Using generic crc32 instructions
2019-05-18 12:39:16 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2019-05-18 12:39:16 0 [Note] InnoDB: Completed initialization of buffer pool
2019-05-18 12:39:16 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-05-18 12:39:16 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-05-18 12:39:16 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-05-18 12:39:16 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-05-18 12:39:16 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-05-18 12:39:16 0 [Note] InnoDB: Waiting for purge to start
2019-05-18 12:39:17 0 [Note] InnoDB: 10.3.13 started; log sequence number 1631167; transaction id 21
2019-05-18 12:39:17 0 [Note] InnoDB: Loading buffer pool(s) from /data/mysql/ib_buffer_pool
2019-05-18 12:39:17 0 [Note] InnoDB: Buffer pool(s) load completed at 190518 12:39:17
2019-05-18 12:39:17 0 [Note] Plugin 'FEEDBACK' is disabled.
2019-05-18 12:39:17 0 [Note] Server socket created on IP: '::'.
2019-05-18 12:39:17 0 [Note] Reading of all Master_info entries succeded
2019-05-18 12:39:17 0 [Note] Added new Master_info '' to hash table
2019-05-18 12:39:17 0 [Note] /usr/bin/mysqld: ready for connections.
Version: '10.3.13-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
[12:39:17] INFO: Starting the Manager...
[5/18/2019] [12:39:21 PM] [Global   ] › ✖  error     Unexpected string /opt/nginx-proxy-manager/node_modules/ajv/lib/data.js:4
 0'multipleOf',
  ^^^^^^^^^^^^
SyntaxError: Unexpected string
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/node_modules/ajv/lib/ajv.js:10:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[12:39:21] INFO: Starting the Manager...

**Comment by FunPsycho** [comment]
Then just repeats that error over and over. Opening the UI gives a ERR_CONNECTION_REFUSED error

**Comment by FunPsycho** [comment]
It was my memory card.  I switched it out and now everything is running fine.  

Thanks for looking into it for at least a little bit!
