### ISSUE TITLE
LetsEncrypt certs cannot be created or renewed

### ISSUE THREAD

**Issue by mra282** [hassio-addons/addon-nginx-proxy-manager#193]
# Problem/Motivation

>LetsEncrypt certs cannot be created or renewed.

## Expected behavior

> LetsEncrypt certs can be created and renewed

## Actual behavior

> User receives Internal Error response when trying to request a new cert or renew an existing cert

**Comment by johny-mnemonic** [comment]
Mine HA install seems to be affected as well. I just got an alert email from letsencrypt, that my certificate needs renewal, so I checked logs and found out, that renewal is not going through.

I have checked the debug log of certbot and here are hopefully the interesting parts (with obfuscated sensitive bits):
```
2021-04-16 03:02:25,060:INFO:certbot._internal.renewal:Cert is due for renewal, auto-renewing...
2021-04-16 03:02:25,060:INFO:certbot._internal.renewal:Non-interactive renewal: random delay of 398.64764565104514 seconds
2021-04-16 03:09:03,786:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-04-16 03:09:03,822:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7522a580>
Prep: True
~~~
2021-04-16 03:09:08,965:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 337
2021-04-16 03:09:08,971:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 16 Apr 2021 01:09:08 GMT
Content-Type: application/json
Content-Length: 337
Connection: keep-alive
Boulder-Requester: 93433957
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/93433957/9091793270
Replay-Nonce: XXXXXXXXXXXXXXXXXX
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-04-23T01:09:08Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "MY.HOME.URL"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12367356443"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/93433957/9091793270"
}
~~~
2021-04-16 03:09:20,300:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/12367356443 HTTP/1.1" 200 1048
2021-04-16 03:09:20,305:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 16 Apr 2021 01:09:20 GMT
Content-Type: application/json
Content-Length: 1048
Connection: keep-alive
Boulder-Requester: 93433957
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: XXXXXXXXXXXXXXXX
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "MY.HOME.URL"
  },
  "status": "invalid",
  "expires": "2021-04-23T01:09:08Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "Fetching http://MY.HOME.URL/.well-known/acme-challenge/XXXXXXXXXXXXXXXX: Timeout during connect (likely firewall problem)",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12367356443/C48ybA",
      "token": "XXXXXXXXXXXXXXXX",
      "validationRecord": [
        {
          "url": "http://MY.HOME.URL/.well-known/acme-challenge/XXXXXXXXXXXXXXXX",
          "hostname": "MY.HOME.URL",
          "port": "80",
          "addressesResolved": [
            "MY.HOME.IP"
          ],
          "addressUsed": "MY.HOME.IP"
        }
      ],
      "validated": "2021-04-16T01:09:09Z"
    }
  ]
}
2021-04-16 03:09:20,307:DEBUG:acme.client:Storing nonce: XXXXXXXXXXXXXXXX
2021-04-16 03:09:20,312:WARNING:certbot._internal.auth_handler:Challenge failed for domain MY.HOME.URL
2021-04-16 03:09:20,313:INFO:certbot._internal.auth_handler:http-01 challenge for MY.HOME.URL
2021-04-16 03:09:20,315:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: MY.HOME.URL
Type:   connection
Detail: Fetching http://MY.HOME.URL/.well-known/acme-challenge/XXXXXXXXXXXXXXXX: Timeout during connect (likely firewall problem)

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2021-04-16 03:09:20,321:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-04-16 03:09:20,322:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-04-16 03:09:20,323:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-04-16 03:09:20,324:DEBUG:certbot._internal.plugins.webroot:Removing /data/letsencrypt-acme-challenge/.well-known/acme-challenge/XXXXXXXXXXXXXXXX
2021-04-16 03:09:20,327:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2021-04-16 03:09:20,330:ERROR:certbot._internal.renewal:Failed to renew certificate npm-1 with error: Some challenges have failed.
```
I just made sure this really is not an network issue by randomly picking some VM in datacenter and trying to connect back home:
```
curl -i http://MY.HOME.URL/.well-known/acme-challenge/XXXXXXXXXXXXXXXX
HTTP/1.1 404 Not Found
Server: nginx
Date: Fri, 16 Apr 2021 01:00:15 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
It obviously gets as far as to the nginx running in this HA addon.

So it probably boils down to this part of the error advice: "If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided." Which I am not sure how to verify.
The timeout error could also mean, that certbot does something nasty to the nginx during the certificate renewal, so instead of serving the challenge file it stops responding completely...

Any help appreciated.

**Comment by Stupco** [comment]
Same issue here.

Version | core-2021.4.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.109
CPU Architecture | x86_64

Nginx Proxy Manager
Current version: 0.10.1

```
[4/21/2021] [9:18:48 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[4/21/2021] [9:19:16 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
Challenge failed for domain website.duckdns.org
Failed to renew certificate npm-14 with error: Some challenges have failed.
Challenge failed for domain website.duckdns.org
Failed to renew certificate npm-8 with error: Some challenges have failed.
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/npm-14/fullchain.pem (failure)
  /etc/letsencrypt/live/npm-8/fullchain.pem (failure)
2 renew failure(s), 0 parse failure(s)
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
Connection Error: Error: read ECONNRESET
Connection Error: Error: read ECONNRESET
[4/21/2021] [9:45:38 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/21/2021] [9:45:38 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #28: website.duckdns.org
[4/21/2021] [9:45:43 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/21/2021] [9:45:43 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-28" --agree-tos --email "myemail@gmail.com" --preferred-challenges "dns,http" --domains "website.duckdns.org" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Performing the following challenges:
http-01 challenge for website.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain website.duckdns.org
http-01 challenge for website.duckdns.org
Cleaning up challenges
Some challenges have failed.
[4/21/2021] [9:48:46 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/21/2021] [9:48:46 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #29: website.duckdns.org
[4/21/2021] [9:48:50 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/21/2021] [9:48:50 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-29" --agree-tos --email "myemail@gmail.com" --preferred-challenges "dns,http" --domains "website.duckdns.org" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Performing the following challenges:
http-01 challenge for website.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain website.duckdns.org
http-01 challenge for website.duckdns.org
Cleaning up challenges
Some challenges have failed.
```

**Comment by sayerada** [comment]
Also getting challenge failure for renewal with Lets Encrypt using duckdns.org

**Comment by johny-mnemonic** [comment]
To make sure, there really is no netwrok issue on my side, I tried to re-create the port forwarding rules in my router and I also tried to disable all my "Proxy Hosts" definitions, to make sure there is nothing in Nginx apart from certbot itself, but it didn't help.
```
2021-04-27 03:35:03,077:WARNING:certbot._internal.auth_handler:Challenge failed for domain kitty.klouda.org
2021-04-27 03:35:03,078:INFO:certbot._internal.auth_handler:http-01 challenge for kitty.klouda.org
2021-04-27 03:35:03,081:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: MY.HOME.URL
Type:   unauthorized
Detail: Invalid response from http://MY.HOME.URL/.well-known/acme-challenge/Ih-rhkQL8EZxXXXmrMdJhNavhXkh__KUsh6F0jkn9o0 [MY.HOME.IP]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n"

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2021-04-27 03:35:03,085:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
```
Looks to me like certbot is not creating the challenge page in Nginx for LetsEncrypt to connect to.
This "unauthorized" error looks like it got directed to some of my regular backends requiring authentication.

**Comment by johny-mnemonic** [comment]
😲
I got lucky and my certificate is renewed, but it was just a pure coincidence and I would say, it is also a confirmation of what I already wrote above.
I accidentally pressed "Renew now" button in the UI while the scheduled renewal job was running on the background and it ended like this:
```
[4/30/2021] [1:56:49 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/30/2021] [1:57:01 AM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates for Cert #1: MY.HOME.URL
[4/30/2021] [2:02:17 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[4/30/2021] [2:02:22 AM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
Another instance of Certbot is already running.
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[30/Apr/2021:02:03:21 +0200] - - 200 - GET http MY.HOME.URL "/.well-known/acme-challenge/XXXXXXXXXXXXXXXX" [Client 18.196.96.172] [Length 87] [Gzip -] [Sent-to LOCAL.NET.IP] "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"
[30/Apr/2021:02:03:22 +0200] - - 200 - GET http MY.HOME.URL "/.well-known/acme-challenge/XXXXXXXXXXXXXXXX" [Client 3.22.70.135] [Length 87] [Gzip -] [Sent-to LOCAL.NET.IP] "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"
[30/Apr/2021:02:03:22 +0200] - - 200 - GET http MY.HOME.URL "/.well-known/acme-challenge/XXXXXXXXXXXXXXXX" [Client 64.78.149.164] [Length 87] [Gzip -] [Sent-to LOCAL.NET.IP] "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"
[30/Apr/2021:02:03:22 +0200] - - 200 - GET http MY.HOME.URL "/.well-known/acme-challenge/XXXXXXXXXXXXXXXX" [Client 34.209.232.166] [Length 87] [Gzip -] [Sent-to LOCAL.NET.IP] "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"
[4/30/2021] [2:03:29 AM] [SSL      ] › ℹ  info      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/npm-1.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for MY.HOME.URL
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/npm-1/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Congratulations, all renewals succeeded: 
  /etc/letsencrypt/live/npm-1/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```
Looks like the first certbot process did some steps to configure nginx to start providing "acme-challenge", but something was still missing, while the second certbot process somehow finished it, so that Letsencrypt servers could finally get to it and finish the verification process.
Even in case my assumptions are not correct, this 100% confirms, the error is somewhere in nginx-proxy-manager plugin or certbot itself, as I haven't changed anything since 27.4. when I was testing the actions described in my previous post.
To confirm, that my successful renewal was just a coincidence, I tried to request new ssl cert now and it failed with essentially the same error as in the post above:
```
Domain: NEW.HOME.URL
Type:   unauthorized
Detail: Invalid response from http://NEW.HOME.URL/.well-known/acme-challenge/rY8XCABACZnJsCQYL9A8aZsS9Wbuvzr
XzYzyjmr8poU [2001:1568::14]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 
Not Found</h1></center>\r\n<hr><center>openresty</cente"
```

**Comment by JulioAviles** [comment]
Hi everybody, same issue hope fix it soon  I have tried several time unsuccefully :(  

Any comment or help will be appreciated

**NPM Debug (INTERNAL ERROR) **

>Error:`` Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-17" --agree-tos --email "julioaviles1@hotmail.com" --preferred-challenges "dns,http" --domains "h0m3ass1st3nt.duckdns.org" 
>
>Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Performing the following challenges:
http-01 challenge for h0m3ass1st3nt.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain h0m3ass1st3nt.duckdns.org
http-01 challenge for h0m3ass1st3nt.duckdns.org
Cleaning up challenges
Some challenges have failed.
>
>    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

**NPM REG Add-on**
> [5/17/2021] [12:42:12 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/17/2021] [12:42:12 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #17: h0m3ass1st3nt.duckdns.org
[5/17/2021] [12:42:18 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/17/2021] [12:42:18 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-17" --agree-tos --email "julioaviles1@hotmail.com" --preferred-challenges "dns,http" --domains "h0m3ass1st3nt.duckdns.org" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Performing the following challenges:
http-01 challenge for h0m3ass1st3nt.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain h0m3ass1st3nt.duckdns.org
http-01 challenge for h0m3ass1st3nt.duckdns.org
Cleaning up challenges
Some challenges have failed.
[5/17/2021] [12:51:35 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[5/17/2021] [12:51:36 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/17/2021] [12:51:36 PM] [SSL      ] › ℹ  info      Renew Complete


Regards !!

**Comment by lymanbuttler** [comment]
Also have this issue. Furthermore I tried to uninstall and reinstall NPM addon but it does not work, instead crashing Supervisor

**Comment by johny-mnemonic** [comment]
@lymanbuttler I think there is a mention about cleaning mysql/mariadb database data of this addon when you would like to do a clean reinstall. Did you clean it?

**Comment by lymanbuttler** [comment]
@johny-mnemonic No but everything is working again after rebooting the device and I was able to get my certs.

**Comment by johny-mnemonic** [comment]
OK, I can confirm, that reinstall of the addon fixes the error.

**Comment by JulioAviles** [comment]
@johny-mnemonic Do you mean reintall just NPM addon or mariadb too? ....because I did it just NPM an issue still there !! :(

**Comment by johny-mnemonic** [comment]
@JulioAviles Than you are less lucky then me and @lymanbuttler, because for us just the reinstall of NPM addon fixed it.

**Comment by mra282** [comment]
Issue was solved for me via a change to firewall rules that were blocking http challange
