### ISSUE TITLE
dns-ovh certbot no longer renews records

### ISSUE THREAD

**Issue by jimmyvh** [hassio-addons/addon-nginx-proxy-manager#251]
Trying to add a new SSL certificate for OVH using their DNS challenge
I got the credentials for their API and filled in all the required fields
After clicking 'save', the action fails, with the following log output:

```
Error: Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-3" --agree-tos --email "<redacted>" --domains "*.<redacted>" --authenticator dns-ovh --dns-ovh-credentials "/etc/letsencrypt/credentials/credentials-3"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Performing the following challenges:
dns-01 challenge for <redacted>
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

On a previous HASSOS installation this worked fine. I tried removing and readding it several times to make sure that everything was entered the right way.

**Comment by tykeal** [comment]
I'm getting the same issue, except I'm trying to use the DNS Made Easy provider. Exact same issue.

I'll note that the Let's Encrypt HA addon is working just fine, but since I can't pull certs from that in Nginx Proxy Manager, I'm having to redo my LE setup :-/

I'm trying to switch to Nginx Proxy Manager so that I can more easily add in some various proxied components without having to write a bunch of custom server bits for the official Nginx Home Assistant SSL Proxy

**Comment by pmorange** [comment]
Hi, also opened this related issue : 
https://github.com/hassio-addons/addon-nginx-proxy-manager/issues/277

The solution seems to be an upgrade of dependencies (at least certbot).
