### ISSUE TITLE
Nginx tries to renew cerificates for subdomains that are deleted months ago!

### ISSUE THREAD

**Issue by carsten-h** [hassio-addons/addon-nginx-proxy-manager#260]
# Problem/Motivation

> It seems that because of this error no certificates are automatically renewed, that need it.

## Expected behavior

> No renew for subdomains that are deleted.

## Actual behavior

> Renew for subdomains that are deleted (subdomain1, subdomain2) months ago is happening.

## Steps to reproduce

> Delete a Host in nginx. I don't know how this could happen.

## Logfile

```
[8/17/2021] [7:32:09 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
Challenge failed for domain subdomain1.abcdef.duckdns.org
Failed to renew certificate npm-2 with error: Some challenges have failed.
Challenge failed for domain subdomain2.abcdef.duckdns.org
Failed to renew certificate npm-4 with error: Some challenges have failed.
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/npm-2/fullchain.pem (failure)
  /etc/letsencrypt/live/npm-4/fullchain.pem (failure)
2 renew failure(s), 0 parse failure(s)
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[17/Aug/2021:19:32:25 +0200] - 200 200 - POST https homeassistant.abcdef.duckdns.org "/api/webhook/0f603339743c49d109d9b1e4dcfe6ded200656214a7e972fa70a4034af298621" [Client 83.135.86.242] [Length 2] [Gzip -] [Sent-to 192.168.178.108] "Home Assistant/2021.8 (io.robbie.HomeAssistant; build:2021.216; iOS 14.7.1)" "-"
[17/Aug/2021:19:32:25 +0200] - 200 200 - POST https homeassistant.abcdef.duckdns.org "/api/webhook/0f603339743c49d109d9b1e4dcfe6ded200656214a7e972fa70a4034af298621" [Client 83.135.86.242] [Length 513] [Gzip -] [Sent-to 192.168.178.108] "Home Assistant/2021.8 (io.robbie.HomeAssistant; build:2021.216; iOS 14.7.1)" "-"
[17/Aug/2021:19:32:25 +0200] - 200 200 - POST https homassistant.abcdef.duckdns.org "/api/webhook/0f603339743c49d109d9b1e4dcfe6ded200656214a7e972fa70a4034af298621" [Client 83.135.86.242] [Length 205] [Gzip -] [Sent-to 192.168.178.108] "Home Assistant/2021.8 (io.robbie.HomeAssistant; build:2021.216; iOS 14.7.1)" "-"
[17/Aug/2021:19:32:34 +0200] - 101 101 - GET https homeassistant.abcdef.duckdns.org "/api/websocket" [Client 83.135.86.242] [Length 189500] [Gzip -] [Sent-to 192.168.178.108] "Home Assistant/2021.8 (io.robbie.HomeAssistant; build:2021.216; iOS 14.7.1)" "-"
[8/17/2021] [8:25:50 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[8/17/2021] [8:31:32 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
Challenge failed for domain subdomain1.abcdef.duckdns.org
Failed to renew certificate npm-2 with error: Some challenges have failed.
Challenge failed for domain subdomain2.abcdef.duckdns.org
Failed to renew certificate npm-4 with error: Some challenges have failed.
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/npm-2/fullchain.pem (failure)
  /etc/letsencrypt/live/npm-4/fullchain.pem (failure)
2 renew failure(s), 0 parse failure(s)
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
[17/Aug/2021:20:48:30 +0200] 444 - GET https 83.135.86.242 "/" [Client 74.120.14.60] [Length 0] [Gzip -] "-" "-"
[17/Aug/2021:20:48:32 +0200] 400 - GET http 83.135.86.242 "/" [Client 74.120.14.60] [Length 248] [Gzip -] "-" "-"
[17/Aug/2021:20:48:32 +0200] 400 - GET http 83.135.86.242 "/" [Client 74.120.14.60] [Length 248] [Gzip -] "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)" "-"
[17/Aug/2021:20:52:12 +0200] 444 - GET https 83.135.86.242 "/actuator/health" [Client 192.241.217.81] [Length 0] [Gzip -] "Mozilla/5.0 zgrab/0.x" "-"
[17/Aug/2021:21:04:17 +0200] 444 - GET https 83.135.86.242 "/" [Client 128.14.133.58] [Length 0] [Gzip -] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
[17/Aug/2021:21:10:18 +0200] 444 - GET https 83.135.86.242 "/" [Client 104.248.22.7] [Length 0] [Gzip -] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17" "-"
[8/17/2021] [9:25:50 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[8/17/2021] [9:32:31 PM] [SSL      ] › ✖  error     Error: Command failed: /usr/bin/certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation  
Challenge failed for domain subdomain1.abcdef.duckdns.org
Failed to renew certificate npm-2 with error: Some challenges have failed.
Challenge failed for domain subdomain2.abcdef.duckdns.org
Failed to renew certificate npm-4 with error: Some challenges have failed.
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/npm-2/fullchain.pem (failure)
  /etc/letsencrypt/live/npm-4/fullchain.pem (failure)
2 renew failure(s), 0 parse failure(s)
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
```

These subdomains are not shown in the hosts list or the SSL certificates list. They are only in the log.

**Comment by carsten-h** [comment]
I have version 0.11.0 running. The problem is still the same!

**Comment by stevehop** [comment]
@carsten-h delete the relevant '.conf' file(s) found in '/ssl/nginxproxymanager/renewal' and then the corresponding folder(s) found in '/ssl/nginxproxymanager/live'

**Comment by carsten-h** [comment]
> delete the relevant '.conf' file(s) found in

Yes, that looks promising. I will see in the next days if it works. The next renewal should take place before November, 12th.

Thank you very much!

**Comment by stevehop** [comment]
If you're happy using the terminal in the nginx container then you can force the renewals using `certbot --force-renewal`

As for why it happens, I'm not sure but have seen it happen a few times hence knowing how to correct it
