### ISSUE TITLE
SSL certificate willbe issued but already expired, and can't renew it: INTERNAL ERROR

### ISSUE THREAD

**Issue by Klagio** [hassio-addons/addon-nginx-proxy-manager#35]
When I try to add a proxy host, all works fine, but when I try to add an Letsencrypt SSL certicates it gives INTERNAL ERROR, but creates a certificate but is expired the date of creation. If I try to renew it manually it gives also internal error

If I try to "ADD  SSL Certificate", I receive an INTERNAL ERROR message, below the log

```

[8/24/2019] [1:51:39 PM] [SSL      ] › ℹ  info      Renewing Let'sEncrypt certificates for Cert #10: xxx-docker.duckdns.org
[8/24/2019] [1:51:40 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot renew -n --force-renewal --disable-hook-validation --cert-name "npm-10" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
No certificate found with name npm-10 (expected /etc/letsencrypt/renewal/npm-10.conf).
```

**Comment by arissaraiva** [comment]
same here, anyone found a solution?

**Comment by Klagio** [comment]
Got stuck, now can't access my https://xxx.duckdns.org, 

Below the log


root@a0d7b954-nginxproxymanager.local.hass.io:/data/logs/letsencrypt$ cat letsencrypt.log
2019-09-06 08:31:41,104:DEBUG:certbot.main:certbot version: 0.30.2
2019-09-06 08:31:41,105:DEBUG:certbot.main:Arguments: ['-n', '--force-renewal', '--disable-hook-validation', '--cert-name', 'npm-4']
2019-09-06 08:31:41,106:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-09-06 08:31:41,131:DEBUG:certbot.log:Root logging level set at 20
2019-09-06 08:31:41,132:INFO:certbot.log:Saving debug log to /data/logs/letsencrypt/letsencrypt.log
2019-09-06 08:31:41,134:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.30.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1271, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3.6/site-packages/certbot/renewal.py", line 394, in handle_renewal_request
    conf_files = [storage.renewal_file_for_certname(config, config.certname)]
  File "/usr/lib/python3.6/site-packages/certbot/storage.py", line 51, in renewal_file_for_certname
    "{1}).".format(certname, path))
certbot.errors.CertStorageError: No certificate found with name npm-4 (expected /etc/letsencrypt/renewal/npm-4.conf).
root@a0d7b954-nginxproxymanager.local.hass.io:/data/logs/letsencrypt$ ^C
root@a0d7b954-nginxproxymanager.local.hass.io:/data/logs/letsencrypt$

**Comment by freaky-m0** [comment]
Same problem here. But i don't know how to access the logfile (/data/logs/letsencrypt/letsencrypt.log). If someone can help me with this i can post the output here.

**Comment by cbho** [comment]
Same experience here - solved when I found, that I had not forwarded port 80 on my router - after doing that and restarting the add-on, certificates were created fine...
