### ISSUE TITLE
Can't login, getting 502 error response and python tracebacks in the log

### ISSUE THREAD

**Issue by wrenoud** [hassio-addons/addon-nginx-proxy-manager#502]
# Problem/Motivation

I can access the login page but I get a "502 Bad Gateway" reply when I try logging in. Everything is otherwise behaving as expected in terms of configured reverse proxies.

I believe I last logged into the manager just before the New Year, which would have been before I updated core to 2024.1.0 (and greater).

## Expected behavior

No issues with logging in.

## Actual behavior

I am continuously getting the following in my log for the addon:

```
[1/9/2024] [1:15:13 AM] [Global   ] › ℹ  info      No valid environment variables for database provided, using default SQLite file '/data/database.sqlite'
[1/9/2024] [1:15:13 AM] [Migrate  ] › ℹ  info      Current database version: none
[1/9/2024] [1:15:13 AM] [Global   ] › ✖  error     Command failed: pip install certbot-dns-duckdns~=0.9  certbot-dns-dynu~=0.0.1 
Traceback (most recent call last):
  File "/usr/bin/pip", line 10, in <module>
    from importlib.metadata import distribution
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "/usr/lib/python3.10/importlib/metadata/_adapters.py", line 5, in <module>
    from ._text import FoldedCase
ValueError: source code string cannot contain null bytes
```

And for completeness here are my current Home Assistant versions:
```txt
Core - 2024.1.2
Supervisor - 2023.12.0
Operating System - 11.3
Frontend - 20240104.0
```

## Steps to reproduce

NA

## Proposed changes

NA

**Comment by wrenoud** [comment]
This appears to have resolved after updating to HAOS 11.4
