### ISSUE TITLE
Enabling SSL leads to stacktrace

### ISSUE THREAD

**Issue by rb2k** [hassio-addons/addon-nginx-proxy-manager#7]
# Problem/Motivation

I tried to enable SSL using letsencrypt, but just ended up with an error popup and a stacktrace in the logs

```
core-ssh:~# hassio info
arch: amd64
channel: stable
hassos: "2.11"
homeassistant: 0.91.4
hostname: hassio
logging: info
machine: qemux86-64
supervisor: "160"
supported_arch:
- amd64
- i386
```

## Expected behavior

It successfully request an SSL cert

## Actual behavior

Javascript alert saying "Internal Error". Stacktrace in the logs:

```
[4/17/2019] [12:43:27 PM] [SSL      ] › ℹ  info      Requesting Let'sEncrypt certificates for Cert #4: home.somedomain.net
2019/04/17 12:43:28 [error] 1524#1524: *241 open() "/var/www/html/HTTPConnTest.txt" failed (2: No such file or directory), client: 192.168.1.1, server: localhost-nginx-proxy-manager, request: "GET /HTTPConnTest.txt HTTP/1.1", host: "d3p8zr0ffa9t17.cloudfront.net"
2019/04/17 12:43:28 [warn] 1524#1524: *241 using uninitialized "server" variable while logging request, client: 192.168.1.1, server: localhost-nginx-proxy-manager, request: "GET /HTTPConnTest.txt HTTP/1.1", host: "d3p8zr0ffa9t17.cloudfront.net"
[17/Apr/2019:12:43:28 -0700] - - 404 - GET http d3p8zr0ffa9t17.cloudfront.net "/HTTPConnTest.txt" [Client 192.168.1.1] [Length 162] [Gzip -] [Sent-to ] "-" "-"
2019/04/17 12:43:28 [error] 1524#1524: *242 open() "/var/www/html/kindle-wifi/wifistub-echo.html" failed (2: No such file or directory), client: 192.168.1.1, server: localhost-nginx-proxy-manager, request: "GET /kindle-wifi/wifistub-echo.html HTTP/1.1", host: "spectrum.s3.amazonaws.com"
2019/04/17 12:43:28 [warn] 1524#1524: *242 using uninitialized "server" variable while logging request, client: 192.168.1.1, server: localhost-nginx-proxy-manager, request: "GET /kindle-wifi/wifistub-echo.html HTTP/1.1", host: "spectrum.s3.amazonaws.com"
[17/Apr/2019:12:43:28 -0700] - - 404 - GET http spectrum.s3.amazonaws.com "/kindle-wifi/wifistub-echo.html" [Client 192.168.1.1] [Length 136] [Gzip 1.30] [Sent-to ] "Java" "-"
[4/17/2019] [12:43:30 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[4/17/2019] [12:43:30 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --cert-name "npm-4" --agree-tos --email "my@email.tld" --preferred-challenges "http" -n -a webroot -d "home.somedomaing.net" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
An unexpected error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))
During handling of the above exception, another exception occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))
Please see the logfiles in /data/logs/letsencrypt for more details.
```

## Steps to reproduce

I installed the addon, forwarded 80 and 443, saw that the regular HTTP works, tried to enable SSL. 443 

## Proposed changes

Not quite sure what's going wrong here.

**Comment by rb2k** [comment]
Hmmm... this MIGHT actually be an issue with port forwarding and my Ubiquiti Dream Machine setup. They have some port forwarding bugs that might lead to this behavior. Closing for now.
